In [9]:
import tkinter as tk
from tkinter import messagebbox as msgbox
def submit():
    username_entry.get()
    password_entry.get()

    window.mainloop()
    window= tk.Toplevel(root)
ulabel = tk.Label(window, text = 'Username')
ulabel = tk.Label.pack()
uentry = tk.Entry(window)
uentry.pack

ImportError: cannot import name 'messagebbox' from 'tkinter' (C:\Users\New\anaconda3\Lib\tkinter\__init__.py)

In [4]:
import pandas as pd
df = pd.read_csv('GIG-logistics(in).csv')

In [5]:
df

,EmployeeID,Name,Department,Role,Email,Phone,Location
0,GIG001,Chukwuemeka Okafor,Operations,Operations Manager,c.okafor@giglogistics.com,8031234567,Lagos
1,GIG002,Adaeze Nwosu,Operations,Dispatch Officer,a.nwosu@giglogistics.com,8031234568,Lagos
2,GIG003,Tunde Adeleke,Operations,Logistics Coordinator,t.adeleke@giglogistics.com,8031234569,Abuja
3,GIG004,Ngozi Eze,Operations,Fleet Supervisor,n.eze@giglogistics.com,8031234570,Lagos
4,GIG005,Emeka Chukwu,Operations,Route Planner,e.chukwu@giglogistics.com,8031234571,Port Harcourt
5,GIG006,Fatima Bello,Operations,Warehouse Officer,f.bello@giglogistics.com,8031234572,Kano
6,GIG007,Seun Adesanya,Operations,Delivery Agent,s.adesanya@giglogistics.com,8031234573,Lagos
7,GIG008,Kelechi Onyekachi,Operations,Delivery Agent,k.onyekachi@giglogistics.com,8031234574,Enugu
8,GIG009,Hauwa Musa,Finance,Chief Finance Officer,h.musa@giglogistics.com,8031234575,Abuja
9,GIG010,Rotimi Adeyemi,Finance,Accountant,r.adeyemi@giglogistics.com,8031234576,Lagos
10,GIG011,Chioma Obi,Finance,Budget Analyst,c.obi@giglogistics.com,8031234577,Lagos
11,GIG012,Yusuf Garba,Finance,Accounts Officer,y.garba@giglogistics.com,8031234578,Kano
12,GIG013,Blessing Okoro,Finance,Payroll Officer,b.okoro@giglogistics.com,8031234579,Port Harcourt
13,GIG014,Taiwo Akinwale,Finance,Internal Auditor,t.akinwale@giglogistics.com,8031234580,Ibadan
14,GIG015,Amina Usman,Human Resources,HR Manager,a.usman@giglogistics.com,8031234581,Abuja
15,GIG016,Ifeanyi Okonkwo,Human Resources,Recruitment Officer,i.okonkwo@giglogistics.com,8031234582,Lagos
16,GIG017,Sade Fashola,Human Resources,Training Coordinator,s.fashola@giglogistics.com,8031234583,Lagos
17,GIG018,Nnamdi Okeke,Human Resources,HR Assistant,n.okeke@giglogistics.com,8031234584,Enugu
18,GIG019,Maryam Abdullahi,Human Resources,Employee Relations Officer,m.abdullahi@giglogistics.com,8031234585,Abuja
19,GIG020,Oluwaseun Balogun,Technology,Head of Technology,o.balogun@giglogistics.com,8031234586,Lagos
20,GIG021,Chidi Nwachukwu,Technology,Software Developer,c.nwachukwu@giglogistics.com,8031234587,Lagos
21,GIG022,Aisha Lawal,Technology,Data Analyst,a.lawal@giglogistics.com,8031234588,Abuja
22,GIG023,Gbenga Adebisi,Technology,IT Support Engineer,g.adebisi@giglogistics.com,8031234589,Lagos
23,GIG024,Nneka Oduya,Technology,Systems Administrator,n.oduya@giglogistics.com,8031234590,Port Harcourt
24,GIG025,Ibrahim Suleiman,Technology,Cybersecurity Analyst,i.suleiman@giglogistics.com,8031234591,Abuja
25,GIG026,Tolulope Ogunwale,Customer Service,Customer Service Manager,t.ogunwale@giglogistics.com,8031234592,Lagos
26,GIG027,Esther Aniemeka,Customer Service,Customer Support Officer,e.aniemeka@giglogistics.com,8031234593,Lagos
27,GIG028,Biodun Ojo,Customer Service,Customer Support Officer,b.ojo@giglogistics.com,8031234594,Ibadan
28,GIG029,Rukayat Folarin,Customer Service,Complaints Resolution Officer,r.folarin@giglogistics.com,8031234595,Lagos
29,GIG030,Chinedu Obiora,Customer Service,Call Centre Agent,c.obiora@giglogistics.com,8031234596,Enugu
30,GIG031,Damilola Akintola,Sales,Sales Manager,d.akintola@giglogistics.com,8031234597,Lagos
31,GIG032,Uche Okereke,Sales,Business Development Officer,u.okereke@giglogistics.com,8031234598,Port Harcourt
32,GIG033,Zainab Idris,Sales,Key Account Manager,z.idris@giglogistics.com,8031234599,Kano
33,GIG034,Femi Adeyinka,Sales,Sales Executive,f.adeyinka@giglogistics.com,8031234600,Lagos
34,GIG035,Precious Igwe,Sales,Sales Executive,p.igwe@giglogistics.com,8031234601,Owerri
35,GIG036,Lara Oduola,Marketing,Marketing Manager,l.oduola@giglogistics.com,8031234602,Lagos
36,GIG037,Tochukwu Eze,Marketing,Digital Marketing Officer,t.eze@giglogistics.com,8031234603,Lagos
37,GIG038,Hadiza Yakubu,Marketing,Brand Officer,h.yakubu@giglogistics.com,8031234604,Abuja
38,GIG039,Victor Osemeka,Marketing,Content Creator,v.osemeka@giglogistics.com,8031234605,Lagos
39,GIG040,Chidinma Nwofor,Marketing,Social Media Manager,c.nwofor@giglogistics.com,8031234606,Lagos

In [11]:
df_useful = df[['Name', 'Department']]
df_useful

                  Name        Department
0   Chukwuemeka Okafor        Operations
1         Adaeze Nwosu        Operations
2        Tunde Adeleke        Operations
3            Ngozi Eze        Operations
4         Emeka Chukwu        Operations
5         Fatima Bello        Operations
6        Seun Adesanya        Operations
7    Kelechi Onyekachi        Operations
8           Hauwa Musa           Finance
9       Rotimi Adeyemi           Finance
10          Chioma Obi           Finance
11         Yusuf Garba           Finance
12      Blessing Okoro           Finance
13      Taiwo Akinwale           Finance
14         Amina Usman   Human Resources
15     Ifeanyi Okonkwo   Human Resources
16        Sade Fashola   Human Resources
17        Nnamdi Okeke   Human Resources
18    Maryam Abdullahi   Human Resources
19   Oluwaseun Balogun        Technology
20     Chidi Nwachukwu        Technology
21         Aisha Lawal        Technology
22      Gbenga Adebisi        Technology
23         Nneka Oduya        Technology
24    Ibrahim Suleiman        Technology
25   Tolulope Ogunwale  Customer Service
26     Esther Aniemeka  Customer Service
27          Biodun Ojo  Customer Service
28     Rukayat Folarin  Customer Service
29      Chinedu Obiora  Customer Service
30   Damilola Akintola             Sales
31        Uche Okereke             Sales
32        Zainab Idris             Sales
33       Femi Adeyinka             Sales
34       Precious Igwe             Sales
35         Lara Oduola         Marketing
36        Tochukwu Eze         Marketing
37       Hadiza Yakubu         Marketing
38      Victor Osemeka         Marketing
39     Chidinma Nwofor         Marketing

In [13]:
df_useful=df[['Role', 'Email', 'Phone']]
df_useful

                             Role                         Email       Phone
0              Operations Manager     c.okafor@giglogistics.com  8031234567
1                Dispatch Officer      a.nwosu@giglogistics.com  8031234568
2           Logistics Coordinator    t.adeleke@giglogistics.com  8031234569
3                Fleet Supervisor        n.eze@giglogistics.com  8031234570
4                   Route Planner     e.chukwu@giglogistics.com  8031234571
5               Warehouse Officer      f.bello@giglogistics.com  8031234572
6                  Delivery Agent   s.adesanya@giglogistics.com  8031234573
7                  Delivery Agent  k.onyekachi@giglogistics.com  8031234574
8           Chief Finance Officer       h.musa@giglogistics.com  8031234575
9                      Accountant    r.adeyemi@giglogistics.com  8031234576
10                 Budget Analyst        c.obi@giglogistics.com  8031234577
11               Accounts Officer      y.garba@giglogistics.com  8031234578
12                Payroll Officer      b.okoro@giglogistics.com  8031234579
13               Internal Auditor   t.akinwale@giglogistics.com  8031234580
14                     HR Manager      a.usman@giglogistics.com  8031234581
15            Recruitment Officer    i.okonkwo@giglogistics.com  8031234582
16           Training Coordinator    s.fashola@giglogistics.com  8031234583
17                   HR Assistant      n.okeke@giglogistics.com  8031234584
18     Employee Relations Officer  m.abdullahi@giglogistics.com  8031234585
19             Head of Technology    o.balogun@giglogistics.com  8031234586
20             Software Developer  c.nwachukwu@giglogistics.com  8031234587
21                   Data Analyst      a.lawal@giglogistics.com  8031234588
22            IT Support Engineer    g.adebisi@giglogistics.com  8031234589
23          Systems Administrator      n.oduya@giglogistics.com  8031234590
24          Cybersecurity Analyst   i.suleiman@giglogistics.com  8031234591
25       Customer Service Manager   t.ogunwale@giglogistics.com  8031234592
26       Customer Support Officer   e.aniemeka@giglogistics.com  8031234593
27       Customer Support Officer        b.ojo@giglogistics.com  8031234594
28  Complaints Resolution Officer    r.folarin@giglogistics.com  8031234595
29              Call Centre Agent     c.obiora@giglogistics.com  8031234596
30                  Sales Manager   d.akintola@giglogistics.com  8031234597
31   Business Development Officer    u.okereke@giglogistics.com  8031234598
32            Key Account Manager      z.idris@giglogistics.com  8031234599
33                Sales Executive   f.adeyinka@giglogistics.com  8031234600
34                Sales Executive       p.igwe@giglogistics.com  8031234601
35              Marketing Manager     l.oduola@giglogistics.com  8031234602
36      Digital Marketing Officer        t.eze@giglogistics.com  8031234603
37                  Brand Officer     h.yakubu@giglogistics.com  8031234604
38                Content Creator    v.osemeka@giglogistics.com  8031234605
39           Social Media Manager     c.nwofor@giglogistics.com  8031234606